FROM python:3.11


# Set the working directory in the container
WORKDIR /code

# Copy the requirements file into the container
COPY ./requirements.txt /code/requirements.txt





RUN python -m venv myenv
RUN source myenv/bin/activate
RUN pip install -r requirements.txt
RUN apt-get install -y libgl1



COPY . /code


# Expose port 8000 to the outside world
EXPOSE 8000


# Command to run the application
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
